sudo: false

language: ruby

rvm:
- 2.3.1
jdk:
- oraclejdk8

env:
  global:
    - export LC_CTYPE=ja_JP.UTF-8
    - GIT_COMMITTER_NAME=kubosho_
    - GIT_COMMITTER_EMAIL=ta2@o2p.jp
    - GIT_AUTHOR_NAME=kubosho_
    - GIT_AUTHOR_EMAIL=ta2@o2p.jp
    - REDPEN_URL=https://github.com/recruit-tech/redpen/releases/download
    - REDPEN_VER=1.6.2
    - NODEJS_VER=6.2.2

install:
  - curl -OL $REDPEN_URL/v$REDPEN_VER/redpen-$REDPEN_VER.tar.gz
  - tar xvf redpen-$REDPEN_VER.tar.gz
  - nvm install $NODEJS_VER
  - nvm use $NODEJS_VER
  - bundle install
  - npm install

cache:
  directories:
  - vendor/bundle
  - node_modules
